


assert 1 == 1
print "success"


raise Exception('wtf?')
